### ISSUE TITLE
I have implemented a remote health monitoring system on ifogsim and I want to schedule sensors data into urgent and not urgent how can I do that please ?

### ISSUE THREAD

**Issue by SWENGINEERJUNIOR** [harshitgupta1337/fogsim#22]
_Originally posted by @ELSIBRO in https://github.com/harshitgupta1337/fogsim/issues/5#issuecomment-428519747_

**Comment by rohitagarwal05** [comment]
Hey have you complete this health monitoring system , i need your help regarding the implementation of this ? 

Can you help ?

**Comment by pushkal00** [comment]
Could you please provide some favour for the implementation of this task.

**Comment by FWHDeveloper** [comment]
Sorry I'm no longer working on this

**Comment by ShubhamTripathi1** [comment]
could you share your health monitoring project anyone?

**Comment by ShubhamTripathi1** [comment]
> Hey have you complete this health monitoring system , i need your help regarding the implementation of this ?
> 
> Can you help ?

have you completed?

**Comment by FWHDeveloper** [comment]
Sorry I'm no longer working on it
